/* Autogenerated file, overwritten by uNmINeD on map generation. */
var UnminedMapProperties = {
    minZoom: -6,
    maxZoom: 0,
    defaultZoom: 0,
    imageFormat: "jpeg",
    minRegionX: -23,
    minRegionZ: -10,
    maxRegionX: 26,
    maxRegionZ: 29,
    worldName: "DevenSMP S13",
    background: "",
    markers: new Array(),
    enableGrid: true,
    showGrid: true,
    centerX: 0,
    centerZ: 0
}
