/* Autogenerated file, overwritten by uNmINeD on map generation. */
var UnminedMapProperties = {
    minZoom: -2,
    maxZoom: 3,
    defaultZoom: 0,
    imageFormat: "webp",
    minRegionX: -10,
    minRegionZ: -8,
    maxRegionX: 18,
    maxRegionZ: 20,
    worldName: "DevenSMP S13",
    background: "",
    markers: new Array(),
    enableGrid: true,
    showGrid: true,
    centerX: 0,
    centerZ: 0
}
