/* Autogenerated file, overwritten by uNmINeD on map generation. */
var UnminedMapProperties = {
    minZoom: -6,
    maxZoom: 0,
    defaultZoom: 0,
    imageFormat: "jpeg",
    minRegionX: -1,
    minRegionZ: -1,
    maxRegionX: 0,
    maxRegionZ: 0,
    worldName: "DevenSMP",
    background: "",
    markers: new Array(),
    enableGrid: true,
    showGrid: true,
    centerX: 0,
    centerZ: 0
}
