/* Autogenerated file, overwritten by uNmINeD on map generation. */
var UnminedMapProperties = {
    minZoom: -1,
    maxZoom: 2,
    defaultZoom: 0,
    imageFormat: "webp",
    minRegionX: -17,
    minRegionZ: -13,
    maxRegionX: 3,
    maxRegionZ: 0,
    worldName: "DevenSMP S13",
    background: "",
    markers: new Array(),
    enableGrid: true,
    showGrid: true,
    centerX: 0,
    centerZ: 0
}
