/* Autogenerated file, overwritten by uNmINeD on map generation. */
var UnminedMapProperties = {
    minZoom: 0,
    maxZoom: 2,
    defaultZoom: 0,
    imageFormat: "webp",
    minRegionX: -2,
    minRegionZ: -9,
    maxRegionX: 11,
    maxRegionZ: 5,
    worldName: "DevenSMP S13",
    background: "",
    markers: new Array(),
    enableGrid: true,
    showGrid: true,
    centerX: 0,
    centerZ: 0
}
