name: live-map-update

permissions:
  contents: write

on:
  schedule:
    - cron: "0 0,12 * * *"
      timezone: Asia/Jakarta
  workflow_dispatch:

jobs:
  update-map:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Download world
        env:
          SERVER_ID: ${{ secrets.PTERODACTYL_SERVERID }}
          API_KEY: ${{ secrets.PTERODACTYL_APIKEY }}
        run: |
          RESPONSE=$(curl "https://panel.freezehost.pro/api/client/servers/$SERVER_ID/backups" -H "Authorization: Bearer $API_KEY" -H "Accept: Application/vnd.pterodactyl.v1+json" -H "Content-Type: application/json")
          UUID=$(echo "$RESPONSE" | jq -r '.data | map(select(.attributes.is_successful == true)) | sort_by(.attributes.created_at) | last | .attributes.uuid')
          DOWNLOAD_RESPONSE=$(curl "https://panel.freezehost.pro/api/client/servers/$SERVER_ID/backups/$UUID/download" -H "Authorization: Bearer $API_KEY" -H "Accept: Application/vnd.pterodactyl.v1+json" -H "Content-Type: application/json")
          DOWNLOAD_LINK=$(echo "$DOWNLOAD_RESPONSE" | jq -r '.attributes.url')
          mkdir .github/livemap
          curl -L "$DOWNLOAD_LINK" -o ".github/livemap/world.tar.gz"
          tar -xzf ".github/livemap/world.tar.gz" -C .github/livemap

      - name: Generate map
        run: |
          ./.github/unmined/unmined-cli web render --world=.github/livemap/worlds/DevenSMP --output=.github/livemap/overworld --dimension=overworld --shadows=true --imageformat=webp --zoomout=-1 --zoomin=2
          ./.github/unmined/unmined-cli web render --world=.github/livemap/worlds/DevenSMP --output=.github/livemap/nether --dimension=nether --shadows=true --imageformat=webp --zoomout=-1 --zoomin=2
  
      - name: Move files
        run: |
          for dimension in overworld nether; do
            rm -f js/livemap/$dimension/properties.js
            mv .github/livemap/$dimension/unmined.map.properties.js js/livemap/$dimension/properties.js
            rm -f js/livemap/$dimension/regions.js
            mv .github/livemap/$dimension/unmined.map.regions.js js/livemap/$dimension/regions.js
            rm -rf assets/images/livemap/tiles/$dimension
            mv .github/livemap/$dimension/tiles/* assets/images/livemap/tiles/$dimension
          done

      - name: Clean Up Files
        run: |
          rm -rf .github/livemap

      - name: Commit Changes
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config --global http.postBuffer 524288000
          git config --global http.lowSpeedLimit 0
          git config --global http.lowSpeedTime 600
          git config --global user.name "github-actions"
          git config --global user.email "actions@github.com"
          git add .
          git commit -m "Updated live map $(date)" || echo "No changes to commit"
          git push origin main
