name: live-map-update

on:
  schedule:
    - cron: "0 * * * *"
  workflow_dispatch:

jobs:
  update-map:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install dependencies
        run: |
          sudo apt update
          sudo apt install -y rsync sshpass tar

      - name: Download uNmINeD CLI
        run: |
          curl -L -o unmined.tar.gz https://unmined.net/download/unmined-cli-linux-x64-dev
          mkdir -p unmined
          tar -xvzf unmined.tar.gz -C unmined --strip-components=1
          chmod +x unmined/unmined-cli

      - name: Download Minecraft World via SFTP
        env:
          SFTP_HOST: ${{ secrets.SFTP_HOST }}
          SFTP_PORT: ${{ secrets.SFTP_PORT }}
          SFTP_USER: ${{ secrets.SFTP_USER }}
          SFTP_PASSWORD: ${{ secrets.SFTP_PASSWORD }}
        run: |
          mkdir -p world
          sshpass -p "$SFTP_PASSWORD" rsync -avz --delete -e "ssh -p $SFTP_PORT -o StrictHostKeyChecking=no" "$SFTP_USER@$SFTP_HOST:worlds/DevenSMP/" world/

      - name: Generate Map with uNmINeD
        run: |
          mkdir -p live
          ./unmined/unmined-cli render --world="world" --output="live"

      - name: Organize uNmINeD Output
        run: |
          mv live/index.html live/map.html
          echo "Map generation and organization complete."

      - name: Deploy to Cloudflare Pages
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "actions@github.com"
          git add .
          git commit -m "Updated live map $(date)" || echo "No changes to commit"
          git push
