name: live-map-update

permissions:
  contents: write

on:
  schedule:
    - cron: "0 * * * *"
  workflow_dispatch:

jobs:
  update-map:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install dependencies
        run: |
          sudo apt update
          sudo apt install -y sshpass tar

      - name: Download Minecraft World via SFTP
        env:
          SFTP_HOST: ${{ secrets.SFTP_HOST }}
          SFTP_PORT: ${{ secrets.SFTP_PORT }}
          SFTP_USER: ${{ secrets.SFTP_USER }}
          SFTP_PASSWORD: ${{ secrets.SFTP_PASSWORD }}
        run: |
          mkdir .github/world
          sshpass -p "$SFTP_PASSWORD" sftp -o StrictHostKeyChecking=no -P $SFTP_PORT $SFTP_USER@$SFTP_HOST <<EOF
          lcd .github/world
          get -r worlds/DevenSMP/*
          bye
          EOF

      - name: Generate Map with uNmINeD
        run: |
          mkdir .github/map
          ./.github/unmined/unmined-cli web render --world=".github/world" --output=".github/map"
          rm -rf assets/images/livemap/tiles
          mv .github/map/tiles assets/images/livemap/
          rm -rf js/livemap.properties.js
          mv .github/map/unmined.map.properties.js js/livemap.properties.js

      - name: Clean Up Files
        run: |
          rm -rf .github/world
          rm -rf .github/map

      - name: Commit Changes
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "actions@github.com"
          git add .
          git commit -m "Updated live map $(date)" || echo "No changes to commit"
          git push origin main
